import type { Employee, AttendanceRecord, LeaveRequest, LeaveBalance, Payslip, NotificationItem } from '../types/api';

/**
 * Generate Login ID in format: [Company Prefix (2)] + [First 2 of First & Last Name (4)] + [Year (4)] + [Serial (4)]
 * Example: Odoo India, John Doe, 2022, 1 -> OIJODO20220001
 */
export function generateLoginId(companyName: string, firstName: string, lastName: string, year: number, serial: number): string {
  const companyPrefix = (companyName.replace(/[^a-zA-Z]/g, '').slice(0, 2) || 'OI').toUpperCase();
  const first2 = (firstName.replace(/[^a-zA-Z]/g, '').slice(0, 2) || 'JO').toUpperCase();
  const last2 = (lastName.replace(/[^a-zA-Z]/g, '').slice(0, 2) || 'DO').toUpperCase();
  const serialStr = String(serial).padStart(4, '0');
  return `${companyPrefix}${first2}${last2}${year}${serialStr}`;
}

export const INITIAL_EMPLOYEE: Employee = {
  id: 'emp-001',
  loginId: 'OIJODO20220001',
  name: 'John Doe',
  email: 'john.doe@odoo.com',
  phone: '+91 98765 43210',
  company: 'Odoo India',
  department: 'Engineering',
  jobTitle: 'Senior Frontend Developer',
  manager: 'Sarah Jenkins',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
  role: 'employee',
  workStatus: 'present',
  joinedYear: 2022,
  serialNo: '0001',

  about: 'Passionate Frontend Engineer specializing in modern JavaScript frameworks, design systems, and responsive UX.',
  skills: ['React', 'TypeScript', 'Astro', 'Tailwind CSS', 'Framer Motion', 'GraphQL'],
  certifications: ['AWS Certified Cloud Practitioner', 'Meta Frontend Developer Professional'],
  interests: ['Open Source', 'UI Design', 'Cycling', 'Chess'],

  dob: '1995-06-15',
  residingAddress: '42 Silicon Avenue, Tech Park, Bengaluru, India 560100',
  nationality: 'Indian',
  gender: 'Male',
  maritalStatus: 'Single',

  bankDetails: {
    accountNumber: '918237465012',
    bankName: 'HDFC Bank',
    ifscCode: 'HDFC0001234',
    panNo: 'ABCDE1234F',
    uanNo: '100987654321',
    empCode: 'EMP-2022-001',
  },

  salaryInfo: {
    monthWage: 50000,
    yearlyWage: 600000,
    basicSalary: 25000,
    houseRentAllowance: 12500,
    standardAllowance: 4165,
    performanceBonus: 4165,
    leaveTravelAllowance: 2085,
    fixedAllowance: 2085,
    pfContributionEmployee: 3000,
    pfContributionEmployer: 3000,
    professionalTax: 200,
    noOfWorkingDaysPerWeek: 5,
  },
};

export const MOCK_COLLEAGUES: Employee[] = [
  INITIAL_EMPLOYEE,
  {
    id: 'emp-002',
    loginId: 'OISAME20220002',
    name: 'Sarah Jenkins',
    email: 'sarah.j@odoo.com',
    phone: '+91 98765 43211',
    company: 'Odoo India',
    department: 'Engineering',
    jobTitle: 'Engineering Manager',
    manager: 'Alex Mercer',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    role: 'admin',
    workStatus: 'present',
    joinedYear: 2022,
    serialNo: '0002',
  },
  {
    id: 'emp-003',
    loginId: 'OIMIAM20230003',
    name: 'Michael Chen',
    email: 'michael.c@odoo.com',
    phone: '+91 98765 43212',
    company: 'Odoo India',
    department: 'Product',
    jobTitle: 'Product Manager',
    manager: 'Sarah Jenkins',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    role: 'employee',
    workStatus: 'on_leave',
    joinedYear: 2023,
    serialNo: '0003',
  },
  {
    id: 'emp-004',
    loginId: 'OIPASM20230004',
    name: 'Priya Sharma',
    email: 'priya.s@odoo.com',
    phone: '+91 98765 43213',
    company: 'Odoo India',
    department: 'Design',
    jobTitle: 'Lead UX Designer',
    manager: 'Michael Chen',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    role: 'employee',
    workStatus: 'present',
    joinedYear: 2023,
    serialNo: '0004',
  },
  {
    id: 'emp-005',
    loginId: 'OIARVI20240005',
    name: 'Arjun Verma',
    email: 'arjun.v@odoo.com',
    phone: '+91 98765 43214',
    company: 'Odoo India',
    department: 'Engineering',
    jobTitle: 'Backend Developer',
    manager: 'Sarah Jenkins',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    role: 'employee',
    workStatus: 'absent',
    joinedYear: 2024,
    serialNo: '0005',
  },
  {
    id: 'emp-006',
    loginId: 'OIEMPA20240006',
    name: 'Emily Patel',
    email: 'emily.p@odoo.com',
    phone: '+91 98765 43215',
    company: 'Odoo India',
    department: 'HR',
    jobTitle: 'HR Specialist',
    manager: 'Sarah Jenkins',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80',
    role: 'hr_officer',
    workStatus: 'present',
    joinedYear: 2024,
    serialNo: '0006',
  },
];

export const MOCK_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-101',
    employeeId: 'emp-001',
    employeeName: 'John Doe',
    date: '2026-08-22',
    dayOfWeek: 'Saturday',
    checkIn: '09:00 AM',
    checkOut: '06:00 PM',
    workHours: '09:00',
    extraHours: '01:00',
    status: 'present',
  },
  {
    id: 'att-102',
    employeeId: 'emp-001',
    employeeName: 'John Doe',
    date: '2026-08-21',
    dayOfWeek: 'Friday',
    checkIn: '09:15 AM',
    checkOut: '05:45 PM',
    workHours: '08:30',
    extraHours: '00:30',
    status: 'present',
  },
  {
    id: 'att-103',
    employeeId: 'emp-001',
    employeeName: 'John Doe',
    date: '2026-08-20',
    dayOfWeek: 'Thursday',
    checkIn: '09:00 AM',
    checkOut: '01:30 PM',
    workHours: '04:30',
    extraHours: '00:00',
    status: 'half_day',
  },
  {
    id: 'att-104',
    employeeId: 'emp-001',
    employeeName: 'John Doe',
    date: '2026-08-19',
    dayOfWeek: 'Wednesday',
    checkIn: '09:05 AM',
    checkOut: '06:00 PM',
    workHours: '08:55',
    extraHours: '00:55',
    status: 'present',
  },
  {
    id: 'att-105',
    employeeId: 'emp-001',
    employeeName: 'John Doe',
    date: '2026-08-18',
    dayOfWeek: 'Tuesday',
    checkIn: '09:00 AM',
    checkOut: '06:00 PM',
    workHours: '09:00',
    extraHours: '01:00',
    status: 'present',
  },
  {
    id: 'att-106',
    employeeId: 'emp-001',
    employeeName: 'John Doe',
    date: '2026-08-17',
    dayOfWeek: 'Monday',
    checkIn: '--:--',
    checkOut: '--:--',
    workHours: '00:00',
    extraHours: '00:00',
    status: 'on_leave',
  },
];

export const MOCK_LEAVE_BALANCE: LeaveBalance = {
  paidDaysAvailable: 24,
  sickDaysAvailable: 7,
  unpaidDaysTaken: 0,
};

export const MOCK_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'leave-201',
    employeeId: 'emp-001',
    employeeName: 'John Doe',
    leaveType: 'Paid Time Off',
    startDate: '2026-09-10',
    endDate: '2026-09-12',
    daysCount: 3,
    status: 'approved',
    reason: 'Family vacation trip',
    adminComment: 'Approved by Sarah Jenkins. Enjoy your trip!',
    createdAt: '2026-08-15',
  },
  {
    id: 'leave-202',
    employeeId: 'emp-001',
    employeeName: 'John Doe',
    leaveType: 'Sick Leave',
    startDate: '2026-08-04',
    endDate: '2026-08-04',
    daysCount: 1,
    status: 'approved',
    attachmentName: 'medical_certificate.pdf',
    reason: 'Dental checkup & rest',
    adminComment: 'Medical certificate verified.',
    createdAt: '2026-08-03',
  },
  {
    id: 'leave-203',
    employeeId: 'emp-001',
    employeeName: 'John Doe',
    leaveType: 'Paid Time Off',
    startDate: '2026-10-01',
    endDate: '2026-10-02',
    daysCount: 2,
    status: 'pending',
    reason: 'Personal errand',
    createdAt: '2026-08-20',
  },
];

export const MOCK_PAYSLIPS: Payslip[] = [
  {
    id: 'pay-301',
    employeeId: 'emp-001',
    month: 'July',
    year: 2026,
    grossSalary: 50000,
    netSalary: 46800,
    deductions: 3200,
    paidDays: 22,
    status: 'paid',
  },
  {
    id: 'pay-302',
    employeeId: 'emp-001',
    month: 'June',
    year: 2026,
    grossSalary: 50000,
    netSalary: 46800,
    deductions: 3200,
    paidDays: 21,
    status: 'paid',
  },
  {
    id: 'pay-303',
    employeeId: 'emp-001',
    month: 'May',
    year: 2026,
    grossSalary: 50000,
    netSalary: 46800,
    deductions: 3200,
    paidDays: 22,
    status: 'paid',
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-401',
    title: 'Leave Request Approved',
    message: 'Your Paid Time Off request for Sep 10 - Sep 12 has been approved by Sarah Jenkins.',
    type: 'success',
    createdAt: '2026-08-16T10:30:00Z',
    read: false,
  },
  {
    id: 'notif-402',
    title: 'Payslip Released',
    message: 'Your payslip for July 2026 is now available for view & download.',
    type: 'info',
    createdAt: '2026-08-01T09:00:00Z',
    read: true,
  },
  {
    id: 'notif-403',
    title: 'Attendance Check-in Reminder',
    message: 'Remember to check in before 09:30 AM on working days.',
    type: 'warning',
    createdAt: '2026-07-28T08:30:00Z',
    read: true,
  },
];
